name: DataStax Venice release

on:
  push:
    tags:
      - 'ds-*'

jobs:
  ds-release:
    name: Build docker
    runs-on: ubuntu-latest
    if: github.repository == 'datastax/venice'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build workaround
        run: |
          # Workaround for "Could not find a remote that refers to https://github.com/linkedin/venice"
          git remote add linkedin https://github.com/linkedin/venice.git
          git fetch linkedin


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          ./gradlew assemble --stacktrace --continue --no-daemon -DforkEvery=1 -DmaxParallelForks=1 -x test
          cd docker
          ./build-and-push.sh datastax ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "clients/venice-pulsar/build/libs/*nar,services/venice-standalone/build/libs/venice-standalone-all.jar,clients/venice-admin-tool/build/libs/venice-admin-tool-all.jar,clients/venice-thin-client/build/libs/venice-thin-client-all.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
